services:
  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./core:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - celery
  celery:
    build: .
    command: celery -A core worker -l INFO
    volumes:
      - ./core:/app
    depends_on:
      - redis
  redis:
    image: redis:7-alpine
    hostname: redis
    expose:
      - 6379
