# Generated by Django 3.2 on 2023-02-24 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20230224_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('name', models.CharField(max_length=128)),
                ('bio', models.TextField()),
                ('birth_date', models.DateField()),
                ('location', models.CharField(max_length=64)),
                ('status', models.CharField(max_length=32)),
                ('avatar', models.ImageField(upload_to='media/user/profile/avatar')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.user')),
            ],
        ),
    ]
