# Generated by Django 3.2 on 2023-02-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20230224_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_username',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=256, null=True, unique=True, verbose_name='Email (or) Username'),
        ),
    ]
