# Generated by Django 3.2 on 2023-02-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_email_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_username',
            field=models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='Email (or) Username'),
        ),
    ]
