# Generated by Django 3.2 on 2023-03-10 13:19

from core.utils import user_6_digit
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, default=user_6_digit, max_length=32, unique=True),
        ),
    ]
