# Generated by Django 3.2 on 2023-02-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, default=None, max_length=64, null=True, unique=True),
        ),
    ]
