# Generated by Django 3.2 on 2023-02-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20230224_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_username',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=256, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, db_index=True, default=None, max_length=254, null=True, unique=True),
        ),
    ]
