# Generated by Django 3.2 on 2023-02-24 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20230224_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='follows',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followings', to='accounts.profile'),
        ),
    ]
