# Generated by Django 3.2 on 2023-03-07 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(related_name='following', to='accounts.Profile'),
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
