# Generated by Django 3.2 on 2023-03-10 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, default=datetime.datetime(2023, 3, 10, 16, 40, 20, 854350), max_length=32),
        ),
    ]
