# Generated by Django 3.2 on 2023-03-10 13:11

import accounts.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, default=accounts.models.user.user_6_digit, max_length=32),
        ),
    ]
