# Generated by Django 3.2 on 2023-03-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20230224_1815'),
        ('blog', '0002_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postlike',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postlike',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='save',
            name='post',
        ),
        migrations.RemoveField(
            model_name='save',
            name='profile',
        ),
        migrations.AddField(
            model_name='comment',
            name='who_liked',
            field=models.ManyToManyField(related_name='comments_liked', to='accounts.Profile'),
        ),
        migrations.AddField(
            model_name='post',
            name='who_liked',
            field=models.ManyToManyField(related_name='posts_liked', to='accounts.Profile'),
        ),
        migrations.AddField(
            model_name='post',
            name='who_saved',
            field=models.ManyToManyField(related_name='posts_saved', to='accounts.Profile'),
        ),
        migrations.DeleteModel(
            name='CommentLike',
        ),
        migrations.DeleteModel(
            name='PostLike',
        ),
        migrations.DeleteModel(
            name='Save',
        ),
    ]
