# Generated by Django 3.2 on 2023-03-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20230303_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='banner',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
    ]
